/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package samples

import org.junit.runner.RunWith
import org.scalatest.{FunSuite, Matchers}
import org.scalatestplus.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class GreeterSuite extends FunSuite with Matchers {
  test("Greeter  test") {
    def greeter = new Greeter()
    greeter.greet("Scala") shouldBe "Hello, Scala!"
  }
}
